---
#########################################################
##             GLOBAL PROPERTIES
##########################################################
server_domain: "kant.lab"
apache_work_path: "/var/www/html"
apache_logs: "/var/log/httpd"
apache_refresh: yes

#########################################################
#            SERVER PROPERGIES
#########################################################
server_services:
  - name: "firewalld"
    enabled: no 
    state: "stopped"

server_selinux_mode:      
   state: "disabled"
   

#########################################################
#            APACHE SERVER CONFIGURATIONS
#########################################################
apache_user: "apache"
apache_shell: "/bin/bash"
apache_group: "{{ apache_user | default('apache')}}"
apache_create_vhosts: false
apache_allow_override: "All"
apache_options: "All Indexes FollowSymLinks"
# Los modulos pueden romper la instalacion, si las dependencias estan mal.
#apache_mods_enabled:
#    - rewrite
#    - ssl
#    - mpm_itk_module
apache_mods_disabled: []

#########################################################
#            PHP CONFIGURATIONS FOR GRAV
#########################################################
#------------
# 1.- Main Config
#------------
php_user:  "{{apache_user | default('apache') }}"
php_group: "{{php_user    | default('apache') }}"
php_install_from_source: false
php_enable_webserver: true
php_webserver_daemon: "httpd"
php_packages_state: "present"
php_install_recommends: true
php_executable: "php"
php_packages:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-gd
    - php-mbstring
    - php-pdo
    - php-pecl-apcu
    - php-xml
    - php-curl 
    - php-ctype
    - php-dom
    - php-gd
    - php-json
    - php-mbstring
    - php-openssl
    - php-session
    - php-simplexml
    - php-xml
    - php-zip

#------------
# 2.- PHP ini
#------------- 
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"

#---------
# 3.- OPT Cache
#--------
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "96"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "4096"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "2"
php_opcache_max_file_size: "0"  

#########################################################
#                  WEB CONTENTS DEFINTIONS
#########################################################

# -------------------------------------------------------
# 1.- Grav Installation
# -------------------------------------------------------
#  1.1.- Install GRAV
grav_work_path: "{{apache_work_path|default('/var/www/html') }}"
grav_users_path: "{{ grav_work_path }}/user/accounts" 

# 2.2.- Grav Customizations (password=Training_2025)
grav_users:
  - username: "cdg"
    fullname: "Cesar Delgado"
    adminuser: yes
    hashed_password: "$2y$10$B7eEPyeiWQe9X3nyEnSCU.F03mOhp7KDP2BvBtvNFH6SVBauT5C.C"
    email: "cesar.delgado@econocom.com"
    title: "Administrador"

# 2.3.- Grav Deploy
grav_deploy:

  - name: "Learn2 Skeleton"
    src: "install/learn2-skeleton.zip"
    dest: "{{ grav_work_path | default('/tmp') }}"
    refresh: yes
    template:
      dest: "{{ grav_work_path | default('/tmp') }}/user/data/licenses.yaml"
      content: |
         licenses:
            typhoon: 7FDA84F1-067C4E27-9A22BD39-61793E6E
            lightbox-gallery: 7FDA84F1-067C4E27-9A22BD39-61793E6E
            svg-icons: 7FDA84F1-067C4E27-9A22BD39-61793E6E
    command:
      - "sudo bash -c 'cd {{ grav_work_path | default('/tmp') }} ; bin/gpm install typhoon -y -n -v'"

grav_sites:
  - title: "Kant"
    path: "home"
    root: yes
    
    configs:
      - file: "../.htaccess"
        regexp: "RewriteBase"
        line: "RewriteBase /"      
 


