---
######################################################################
#   PREPARE HOST
######################################################################
- hosts: "webservers"
  become: "true"
  tasks:
    - name: "Prepare Server" 
      include_tasks: "prepare.yml"

######################################################################
##   CREATE WEBSERVER 
#######################################################################
- hosts: "webservers" 
  become: "true"
  roles:
    - "geerlingguy.apache"
    - "geerlingguy.php"  
    - "cdg.vcloud"
    - "cdg.grav"
